### ISSUE TITLE
希望按键键值与按键索引都增加使用宏定义完成

### ISSUE THREAD

**Issue by wdfk-prog** [smartmx/MFBD#1]
例如：定义一个枚举存放按键索引。
一个枚举存放按键键值。
我只要通过宏定义输入按键名称。
就能生成对应的索引与各个状态的键值。这样方便查看与编写。
我尝试过操作，搞不出来。

大概像如下这样的枚举

/* 按键ID*/
typedef enum
{
  KID_Stop_Button = 0X00,
  KID_WK_UP,
  KID_Before_Radar_1,
  KID_Before_Radar_2,
  KID_Before_Radar_3,
  KID_Start_Button,
  KID_Article_Crash,
  KID_Turn_ALM,
  KID_Walk_ALM,
  HARD_KEY_NUM,// 实体按键个数
}KEY_ID;
/*
	定义键值代码, 必须按如下次序定时每个键的按下、弹起和长按事件

	推荐使用enum, 不用#define，原因：
	(1) 便于新增键值,方便调整顺序，使代码看起来舒服点
	(2) 编译器可帮我们避免键值重复。
*/
typedef enum
{
	KEY_NONE = 0X00U,			      /* 0 表示按键事件 */
  
  KEY_WK_UP_DOWN,				      /* 4键按下 */
  KEY_WK_UP_UP,				        /* 4键弹起 */
  KEY_WK_UP_LONG,				      /* 4键长按 */
  
  KEY_TURN_ZERO_DOWN,				  /* 1键按下 */
  KEY_TURN_ZERO_UP,				    /* 1键弹起 */
  KEY_TURN_ZERO_LONG,				  /* 1键长按 */

  KEY_TURN_LIMIT_DOWN,				/* 2键按下 */
  KEY_TURN_LIMIT_UP,				  /* 2键弹起 */
  KEY_TURN_LIMIT_LONG,				/* 2键长按 */
  
  KEY_TURN_ALM_DOWN,				  /* 3键按下 */
  KEY_TURN_ALM_UP,				    /* 3键弹起 */
  KEY_TURN_ALM_LONG,				  /* 3键长按 */
}KEY_CODE;
/*               名称,        按键索引,         滤波时间, 重复时间，长按时间，按下键值,             松开键值          长按键值) */
MFBD_NBTN_DEFINE(STOP_BUTTON, KID_Stop_Button,  3,        0,          150,     KEY_TURN_ZERO_DOWN,   KEY_TURN_ZERO_UP, KEY_TURN_ZERO_LONG);
MFBD_NBTN_DEFINE(turn_limit,  KID_TURN_LIMIT,   3,        0,          150,     KEY_TURN_LIMIT_DOWN,  KEY_TURN_LIMIT_UP,KEY_TURN_LIMIT_LONG);
MFBD_NBTN_DEFINE(turn_alm,    KID_TURN_ALM,     3,        0,          150,     KEY_TURN_ALM_DOWN,    KEY_TURN_ALM_UP,  KEY_TURN_ALM_LONG);
MFBD_NBTN_DEFINE(WK_UP,       KID_WK_UP,        3,        0,          150,     KEY_WK_UP_DOWN,       KEY_WK_UP_UP,     KEY_WK_UP_LONG);

/*               名称,        按键索引,         滤波时间, 重复时间，长按时间，按下键值,             松开键值          长按键值) */
MFBD_NBTN_DEFINE(STOP_BUTTON, KID_Stop_Button,  3,        0,          150,     KEY_TURN_ZERO_DOWN,   KEY_TURN_ZERO_UP, KEY_TURN_ZERO_LONG);
MFBD_NBTN_DEFINE(turn_limit,  KID_TURN_LIMIT,   3,        0,          150,     KEY_TURN_LIMIT_DOWN,  KEY_TURN_LIMIT_UP,KEY_TURN_LIMIT_LONG);
MFBD_NBTN_DEFINE(turn_alm,    KID_TURN_ALM,     3,        0,          150,     KEY_TURN_ALM_DOWN,    KEY_TURN_ALM_UP,  KEY_TURN_ALM_LONG);
MFBD_NBTN_DEFINE(WK_UP,       KID_WK_UP,        3,        0,          150,     KEY_WK_UP_DOWN,       KEY_WK_UP_UP,     KEY_WK_UP_LONG);
/*
*********************************************************************************************************
*	函 数 名: 按键处理函数
*	功能说明: 无
*	形    参: 无
*	返 回 值: 无
*********************************************************************************************************
*/
void Key_Handle(mfbd_btn_code_t ucKeyCode)
{
  if (ucKeyCode != KEY_NONE)
  {
    switch (ucKeyCode)
    {
      case KEY_WK_UP_UP: 
        LOG_I("WK_UP UP");
        break;
      case KEY_WK_UP_DOWN:
        LOG_I("WK_UP DOWN");
        break;
      case KEY_WK_UP_LONG:
        LOG_I("WK_UP LONG");
        break;
      case KEY_TURN_ZERO_UP: 
        LOG_I("turn zero sensor UP");
        break;
      case KEY_TURN_ZERO_DOWN:
        LOG_I("turn zero sensor DOWN");
        break;
      case KEY_TURN_ZERO_LONG:
        LOG_I("turn zero sensor LONG");
        break;
      case KEY_TURN_LIMIT_UP: 
        LOG_I("turn limit sensor UP");
        break;
      case KEY_TURN_LIMIT_DOWN:
        LOG_I("turn limit sensor DOWN");
        break;
      case KEY_TURN_LIMIT_LONG:
        LOG_I("turn limit sensor LONG");
        break;
      case KEY_TURN_ALM_UP: 
        LOG_I("turn alm sensor UP");
        break;
      case KEY_TURN_ALM_DOWN:
        LOG_I("turn alm sensor DOWN");
        break;
      case KEY_TURN_ALM_LONG:
        LOG_I("turn alm sensor LONG");
        break;
      default:
        /* 其它的键值不处理 */
        break;
    }
  }
}

**Comment by smartmx** [comment]
想法不错，但是这个不应该由mfbd完成。你打算使用enum定义好变量，而mfbd的define可以直接扩展出那个变量。

**Comment by smartmx** [comment]
这个方案在tiny button和normal button上可行，但是在multibutton上不可行。

**Comment by smartmx** [comment]
想法不错，但是这个不应该由mfbd完成。你打算使用enum定义好变量，而mfbd的define可以直接扩展出那个变量。
这个方案在tiny button和normal button上可行，但是在multi-function button上不可行。
晚上我会添加一下这个代码。

**Comment by smartmx** [comment]
```c
#define MFBD_TBTN_ENUM_DEFINE(NAME, BTN_INDEX)                          \
static const mfbd_tbtn_info_t NAME##_info = {                           \
        NAME##_DOWN_CODE,                                               \
        NAME##__UP_CODE,                                                \
        BTN_INDEX,                                                      \
};                                                                      \
mfbd_tbtn_t NAME = {                                                    \
        &NAME##_info,                                                   \
        0,                                                              \
        0,                                                              \
}
```
按照上面的宏定义即可，如果你的button名为 `hello`，则你需要在枚举中增加`hello__DOWN_CODE`和`__UP_CODE`

**Comment by smartmx** [comment]
api已增加
```c
#define MFBD_NBTN_DEFAULT_DEFINE(NAME, BTN_INDEX, FILTER_TIME, REPEAT_TIME, LONG_TIME)              \
static const mfbd_nbtn_info_t NAME##_info = {                                                       \
        FILTER_TIME,                                                                                \
        REPEAT_TIME,                                                                                \
        LONG_TIME,                                                                                  \
        NAME##_DOWN_CODE,                                                                           \
        NAME##_UP_CODE,                                                                             \
        NAME##_LONG_CODE,                                                                           \
        BTN_INDEX,                                                                                  \
};                                                                                                  \
mfbd_nbtn_t NAME = {                                                                                \
        &NAME##_info,                                                                               \
        0,                                                                                          \
        0,                                                                                          \
}
```

**Comment by wdfk-prog** [comment]
多谢！
