### ISSUE TITLE
配置的宏定义能否进行优化

### ISSUE THREAD

**Issue by wdfk-prog** [smartmx/MFBD#2]
由于更改配置会直接修改mfbd_cfg.h头文件。
导致我在用git 上传代码时，显示：modified:   mfbd_cfg.h

没法上传。就只能删除子模块git文件。变成自己的文件，而且无法获取更新了。

建议在rt_config.h里进行配置就好

**Comment by smartmx** [comment]
这个并不是专为rt-thread使用的，之前都是可以在任意平台使用的，所以没有考虑将配置文件更改。
你可以使用：`git update-index --assume-unchanged file/path`命令来本地忽略该文件即可。

**Comment by wdfk-prog** [comment]
> 多谢。
