### ISSUE TITLE
对于rtt软件包的配置建议

### ISSUE THREAD

**Issue by wdfk-prog** [smartmx/MFBD#3]
### 我最近重新添加了MFDB软件包
- 发现如下配置得修改.h文件，我之前代码手动进行了修改。移植新的代码也得修改一遍
```c
/* set MFBD_USE_TINY_BUTTON to 1 will enable tiny button functions. */
#define MFBD_USE_TINY_BUTTON                0

/* set MFBD_USE_NORMAL_BUTTON to 1 will enable normal button functions. */
#define MFBD_USE_NORMAL_BUTTON              1

/* set MFBD_USE_MULTIFUCNTION_BUTTON to 1 will enable multifunction button functions. */
#define MFBD_USE_MULTIFUCNTION_BUTTON       0

/* set MFBD_USE_BTN_SCAN_PRE_FUNC to 1 will enable running prepare_function before run button detection function */
#define MFBD_USE_BTN_SCAN_PRE_FUNC          0

/* set MFBD_USE_BTN_SCAN_AFTER_FUNC to 1 will enable running after_function after run button detection function */
#define MFBD_USE_BTN_SCAN_AFTER_FUNC        0
```

### 建议
- rtt软件包里面添加配置选项，这样在软件包更新后，不需要重新修改配置

**Comment by smartmx** [comment]
好吧，我尝试一下。

**Comment by smartmx** [comment]
有没有哪个软件包是这么配置的，发个链接给我参考一下。

**Comment by wdfk-prog** [comment]
> 有没有哪个软件包是这么配置的，发个链接给我参考一下。
- 这个是有配置定时器的选择的 https://github.com/gbcwbz/canfestival-rtt#readme
- 应该是要kconfig文件的，不过我没找到。。。。

**Comment by smartmx** [comment]
好的，我这两天看看，改一下。

**Comment by wdfk-prog** [comment]
> 好的，我这两天看看，改一下。

多谢^~^

**Comment by smartmx** [comment]
初步测试可以了，但rt-thread那边的packages更新正在PR中，等那边merge以后，更新packages下面Kconfig那两个文件的就没问题了。你也可以先下载我这边仓库里的文件：[MFBD](https://github.com/smartmx/packages/tree/mfbd_update/misc/MFBD)

**Comment by wdfk-prog** [comment]
> 初步测试可以了，但rt-thread那边的packages更新正在PR中，等那边merge以后，更新packages下面Kconfig那两个文件的就没问题了。你也可以先下载我这边仓库里的文件：[MFBD](https://github.com/smartmx/packages/tree/mfbd_update/misc/MFBD)

- 我已更新测试没问题。多谢~
